"""Seed events shared by the fuzz targets.

Copied from conformance/fixtures/valid/*.json. The targets are bundled with
PyInstaller and cannot read the repository at run time, so the seeds travel as
a module. tests/test_repository_gates.py fails if this copy drifts from the
fixtures.
"""

SEEDS = {'action': {'action_digest': {'algorithm': 'sha256',
                              'value': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'},
            'action_id': 'tool-call-001',
            'action_kind': 'mcp',
            'action_name': 'github.create_pull_request',
            'agent_id': 'spiffe://example.test/agent/coder',
            'approval_id': 'approval-001',
            'duration_ns': 42000000,
            'event_id': '018f0f7d-7a13-7cc2-8000-000000000006',
            'event_type': 'action.executed',
            'operation': 'create',
            'outcome': 'success',
            'policy_event_id': '018f0f7d-7a13-7cc2-8000-000000000001',
            'producer': {'name': 'example-action-adapter', 'version': '0.1.0'},
            'result_digest': {'algorithm': 'sha256',
                              'value': 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'},
            'run_id': 'run-governed-sdlc-001',
            'spec_version': '0.1.0-alpha.4',
            'target': {'id': 'example/repository', 'kind': 'git.repository'},
            'time_unix_nano': '1787079650000000000',
            'workflow_id': 'workflow-build-feature'},
 'approval': {'action_digest': {'algorithm': 'sha256',
                                'value': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'},
              'actor_id': 'reviewer-7d91',
              'actor_type': 'human',
              'agent_id': 'spiffe://example.test/agent/coder',
              'approval_id': 'approval-001',
              'event_id': '018f0f7d-7a13-7cc2-8000-000000000002',
              'event_type': 'approval.approved',
              'producer': {'name': 'example-approval-adapter', 'version': '0.1.0'},
              'requested_at_unix_nano': '1787079500000000000',
              'run_id': 'run-governed-sdlc-001',
              'span_id': '00f067aa0ba902b7',
              'spec_version': '0.1.0-alpha.4',
              'time_unix_nano': '1787079580000000000',
              'trace_id': '4bf92f3577b34da6a3ce929d0e0e4736'},
 'data-flow': {'agent_id': 'spiffe://example.test/agent/architect',
               'classification': {'producer': 'example-dlp',
                                  'taxonomy': 'example.enterprise.v1',
                                  'value': 'confidential'},
               'content_digest': {'algorithm': 'sha256',
                                  'value': 'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc'},
               'destination': {'id': 'architecture-agent', 'kind': 'agent'},
               'direction': 'read',
               'event_id': '018f0f7d-7a13-7cc2-8000-000000000004',
               'event_type': 'data_flow.observed',
               'policy_decision': 'allow',
               'producer': {'name': 'example-dataflow-adapter', 'version': '0.1.0'},
               'purpose': 'generate_architecture',
               'run_id': 'run-governed-sdlc-001',
               'size_bytes': 18342,
               'source': {'id': 'requirements-graph', 'kind': 'knowledge_graph'},
               'spec_version': '0.1.0-alpha.4',
               'time_unix_nano': '1787079400000000000',
               'transformation': 'metadata_only'},
 'evidence': {'capture_profile': 'metadata_only',
              'chain_digest': {'algorithm': 'sha256',
                               'value': 'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd'},
              'completeness': 'complete',
              'event_id': '018f0f7d-7a13-7cc2-8000-000000000005',
              'event_type': 'evidence.run_closed',
              'producer': {'name': 'agentrust-telemetry', 'version': '0.1.0-alpha.4'},
              'run_id': 'run-governed-sdlc-001',
              'sequence': 14,
              'spec_version': '0.1.0-alpha.4',
              'time_unix_nano': '1787079700000000000'},
 'policy-decision': {'action_type': 'repository.write',
                     'agent_id': 'spiffe://example.test/agent/coder',
                     'decision': 'deny',
                     'enforcement_mode': 'enforce',
                     'evaluation_duration_ns': 182000,
                     'event_id': '018f0f7d-7a13-7cc2-8000-000000000001',
                     'event_type': 'policy.decision',
                     'policy': {'bundle_digest': {'algorithm': 'sha256',
                                                  'value': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'},
                                'engine': 'cedar',
                                'engine_version': '4.3.0',
                                'policy_id': 'repo-write'},
                     'producer': {'name': 'example-policy-adapter', 'version': '0.1.0'},
                     'reason_codes': ['BRANCH_PROTECTED'],
                     'resource_type': 'git.repository',
                     'run_id': 'run-governed-sdlc-001',
                     'span_id': '00f067aa0ba902b7',
                     'spec_version': '0.1.0-alpha.4',
                     'time_unix_nano': '1787079600000000000',
                     'trace_id': '4bf92f3577b34da6a3ce929d0e0e4736',
                     'workflow_id': 'workflow-build-feature'},
 'usage': {'agent_id': 'spiffe://example.test/agent/coder',
           'cost': {'amount': 0.0124,
                    'currency': 'USD',
                    'pricing_version': 'provider-2026-08-01',
                    'source': 'provider'},
           'event_id': '018f0f7d-7a13-7cc2-8000-000000000003',
           'event_type': 'usage.recorded',
           'input_tokens': 4200,
           'operation': 'chat',
           'output_tokens': 812,
           'producer': {'name': 'example-usage-adapter', 'version': '0.1.0'},
           'provider': 'example-ai',
           'request_model': 'example-model-2',
           'run_id': 'run-governed-sdlc-001',
           'scope': 'model_call',
           'spec_version': '0.1.0-alpha.4',
           'time_unix_nano': '1787079590000000000',
           'workflow_id': 'workflow-build-feature'}}

RUN_ID = "run-governed-sdlc-001"
